Update Japan website
H-I-S-Vietnam/his-discover pull request #1443
Opened 2021-09-24 02:35 UTC by Katsuhis

his-discover/japan/luxury-journey/en/travel/artistic-japan/index.html

## Type of change

Please choose options by type x inside the square brackets `[x]`.

- [ ] Bug fix (non-breaking change which fixes an issue) (Thay đổi không vi phạm giúp khắc phục sự cố)
- [x] New feature (non-breaking change which adds functionality) (Thay đổi không phá vỡ mà thêm chức năng)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) (sửa chữa hoặc tính năng có thể khiến chức năng hiện có không hoạt động như mong đợi)

## Checklist:

- [ ] My code follows the style guidelines of this project ( Code của tôi tuân theo nguyên tắc về kiểu dáng của dự án)
- [x] I have performed a self-review of my own code ( Tôi đã kiểm tra code của tôi kĩ càng)
- [ ] I have commented my code, particularly in hard-to-understand areas ( Tôi đã có ghi chú trong code, để giúp việc review code dễ dàng hơn)

2021-09-24 03:11 UTC, raymondugv requested changes

2021-09-24 03:11 UTC, raymondugv commented on japan/luxury-journey/en/travel/artistic-japan/index.html
> +    <meta name="description" content="Discover the tasteful contemporary art pieces and the aesthetically pleasing architecture styles of Japan in these sophisticated islands" />
Theo như em hiểu thì chỗ này phải là `og:description` chứ nhỉ

2021-09-29 06:13 UTC, Katsuhis commented on japan/luxury-journey/en/travel/artistic-japan/index.html
> +    <meta name="description" content="Discover the tasteful contemporary art pieces and the aesthetically pleasing architecture styles of Japan in these sophisticated islands" />
Thank you so much!
I will check and collect information 
Could you check it?

2021-09-29 06:19 UTC, raymondugv requested changes

2021-09-29 06:19 UTC, raymondugv commented on japan/luxury-journey/en/travel/artistic-japan/index.html
> +    <meta name="description" content="Discover the tasteful contemporary art pieces and the aesthetically pleasing architecture styles of Japan in these sophisticated islands" />
@Katsuhis san,

I'm still see it as `<meta name="description">` it should be `<meta name="og:description">`.
Please check again.

2021-09-29 06:46 UTC, Katsuhis commented on japan/luxury-journey/en/travel/artistic-japan/index.html
> +    <meta name="description" content="Discover the tasteful contemporary art pieces and the aesthetically pleasing architecture styles of Japan in these sophisticated islands" />
@Lekun san
Sorry I forget Update.
Could you check it again?

2021-09-29 06:55 UTC, raymondugv approved these changes
LGTM.

2021-09-29 06:55 UTC, raymondugv approved these changes
LGTM.

2021-09-29 06:55 UTC, merged